version: "3"  

services:
  goservice:
    build: .
    networks:
      - servicenetwork

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - goservice
    networks:
      - servicenetwork

networks:
  servicenetwork:
    driver: bridge
