version: "3"  

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    image: app
    networks:
      - net
    restart: unless-stopped
    volumes:
      - .:/app
    
  nginx:
    image: nginx
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/etc/nginx/html/public
    depends_on:
      - app
    networks:
      - net

networks:
  net:
    driver: bridge