version: "3"

services:
  my-service:
    build: .
    ports:
      - "9000:9000"
    networks:
      - my-network

  my-nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - my-service
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
