version: "3"  

services:
  app:
    image: app
    container_name: app
    build: .
    networks:
      - net

  nginx:
    image: nginx
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - net

networks:
  net:
    driver: bridge